sonar.projectKey=unaveenj_Gold-Notifier-SG
sonar.organization=unaveenj
sonar.host.url=https://sonarcloud.io

# Python scraper
sonar.sources=scraper,web/app,web/app/api

sonar.exclusions=web/node_modules/**,web/.next/**,**/*.test.*,**/__tests__/**
